### ISSUE TITLE
API error founded!!!

### ISSUE THREAD

**Issue by kaung8229** [kaung8229/githublesson6#1]
I got new error while creating new user!! May be api fetch error!!

**Comment by kaung8229** [comment]
There is the same problem while creating new job title.

**Comment by kaung8229** [comment]
Done by myself.

**Comment by ghost** [comment]
I think this will help you.

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme

you may need to install the c compiler
